services:
    mariadb_sails27:
        image: mariadb:10.11
        restart: unless-stopped
        env_file: ./mariadb/.env
        volumes:
            - ${DATA_FOLDER}/mariadb_data/:/var/lib/mysql
        healthcheck:
            test: mysqladmin ping -u $$MARIADB_USER -p$$MARIADB_PASSWORD --protocol tcp
            interval: 5s
            timeout: 4s
            retries: 10

    redis_sails27:
        image: redis
        restart: unless-stopped
        volumes:
            - ${DATA_FOLDER}/redis_data/:/data/
        entrypoint: redis-server --appendonly yes
        depends_on:
            mariadb_sails27:
                condition: "service_healthy"

    sails27:
        build: 
            context: ./sails-app/src/
            dockerfile: Dockerfile
        env_file: ./sails-app/.env
        restart: unless-stopped
        volumes:
            - ${DATA_FOLDER}/sails_nsir_data/:/app/data
        depends_on:
            mariadb_sails27:
                condition: "service_healthy"
            redis_sails27:
                condition: "service_started"

    php_sails27:
        build:
          dockerfile: Dockerfile
          context: ./php
        restart: unless-stopped
        volumes:
          - ${DATA_FOLDER}/sails_nsir_data/:/www/sails_nsir/

    nginx_sails27:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ${DATA_FOLDER}/sails_nsir_data/:/www/sails_nsir/
        depends_on:
            - sails27

volumes:
    mariadb_data:
        external: true
    redis_data:
        external: true
    sails_nsir_data:
        external: true
